FROM python:3.9-slim

# Install Java (required for Spark)
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y default-jre && \
    apt-get clean

# Install Python packages
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

# Set working directory
WORKDIR /app

# Copy your files
COPY . .

# Set default command
CMD ["python", "main.py"]